2025-01-20 14:27:59,481 INFO:  * Restarting with stat [in /opt/anaconda3/lib/python3.11/site-packages/werkzeug/_internal.py:96]
2025-01-20 14:28:00,003 INFO: Inicializace aplikace... [in /Users/martinmikes/Downloads/my-directus-project/root/supplo.ai/app/__init__.py:47]
2025-01-20 14:28:00,821 INFO: Aplikace byla úspěšně inicializována [in /Users/martinmikes/Downloads/my-directus-project/root/supplo.ai/app/__init__.py:144]
2025-01-20 14:28:00,822 WARNING:  * Debugger is active! [in /opt/anaconda3/lib/python3.11/site-packages/werkzeug/_internal.py:96]
2025-01-20 14:28:00,829 INFO:  * Debugger PIN: 278-609-759 [in /opt/anaconda3/lib/python3.11/site-packages/werkzeug/_internal.py:96]
2025-01-20 14:28:04,652 INFO: Vytvořen základní adresář pro farmy: /Users/martinmikes/Downloads/my-directus-project/root/supplo.ai/app/data/farms [in /Users/martinmikes/Downloads/my-directus-project/root/supplo.ai/app/blueprints/farms.py:18]
2025-01-20 14:28:04,662 INFO: 127.0.0.1 - - [20/Jan/2025 14:28:04] "GET /dashboard/stats HTTP/1.1" 200 - [in /opt/anaconda3/lib/python3.11/site-packages/werkzeug/_internal.py:96]
2025-01-20 14:28:04,693 INFO: Vytvořen základní adresář pro farmy: /Users/martinmikes/Downloads/my-directus-project/root/supplo.ai/app/data/farms [in /Users/martinmikes/Downloads/my-directus-project/root/supplo.ai/app/blueprints/farms.py:18]
2025-01-20 14:28:04,695 INFO: 127.0.0.1 - - [20/Jan/2025 14:28:04] "GET /dashboard/activities HTTP/1.1" 200 - [in /opt/anaconda3/lib/python3.11/site-packages/werkzeug/_internal.py:96]
2025-01-20 14:28:06,928 INFO:  * Detected change in '/Users/martinmikes/Downloads/my-directus-project/root/supplo.ai/run.py', reloading [in /opt/anaconda3/lib/python3.11/site-packages/werkzeug/_internal.py:96]
2025-01-20 14:28:07,173 INFO:  * Restarting with stat [in /opt/anaconda3/lib/python3.11/site-packages/werkzeug/_internal.py:96]
2025-01-20 14:28:07,688 INFO: Inicializace aplikace... [in /Users/martinmikes/Downloads/my-directus-project/root/supplo.ai/app/__init__.py:47]
2025-01-20 14:28:08,512 INFO: Aplikace byla úspěšně inicializována [in /Users/martinmikes/Downloads/my-directus-project/root/supplo.ai/app/__init__.py:144]
2025-01-20 14:28:08,514 WARNING:  * Debugger is active! [in /opt/anaconda3/lib/python3.11/site-packages/werkzeug/_internal.py:96]
2025-01-20 14:28:08,523 INFO:  * Debugger PIN: 278-609-759 [in /opt/anaconda3/lib/python3.11/site-packages/werkzeug/_internal.py:96]
