2025-01-20 20:56:14,830 ERROR: Str√°nka nenalezena: http://127.0.0.1:5001/static/images/3018/products/FA_3018_0029_57.png [in /Users/martinmikes/Downloads/my-directus-project/root/supplo.ai/app/__init__.py:129]
2025-01-20 20:56:14,831 ERROR: Str√°nka nenalezena: http://127.0.0.1:5001/static/images/3018/products/FA_3018_0030_76.png [in /Users/martinmikes/Downloads/my-directus-project/root/supplo.ai/app/__init__.py:129]
2025-01-20 20:56:14,831 INFO: Vytvo≈ôen z√°kladn√≠ adres√°≈ô pro farmy: /Users/martinmikes/Downloads/my-directus-project/root/supplo.ai/app/data/farms [in /Users/martinmikes/Downloads/my-directus-project/root/supplo.ai/app/blueprints/farms.py:18]
2025-01-20 20:56:14,832 INFO: 127.0.0.1 - - [20/Jan/2025 20:56:14] "[33mGET /static/images/3018/products/FA_3018_0028_37.png HTTP/1.1[0m" 404 - [in /opt/anaconda3/lib/python3.11/site-packages/werkzeug/_internal.py:96]
2025-01-20 20:56:14,833 INFO: Vytvo≈ôen z√°kladn√≠ adres√°≈ô pro farmy: /Users/martinmikes/Downloads/my-directus-project/root/supplo.ai/app/data/farms [in /Users/martinmikes/Downloads/my-directus-project/root/supplo.ai/app/blueprints/farms.py:18]
2025-01-20 20:56:14,836 INFO: 127.0.0.1 - - [20/Jan/2025 20:56:14] "[33mGET /static/images/3018/products/FA_3018_0029_57.png HTTP/1.1[0m" 404 - [in /opt/anaconda3/lib/python3.11/site-packages/werkzeug/_internal.py:96]
2025-01-20 20:56:14,836 INFO: 127.0.0.1 - - [20/Jan/2025 20:56:14] "[33mGET /static/images/3018/products/FA_3018_0030_76.png HTTP/1.1[0m" 404 - [in /opt/anaconda3/lib/python3.11/site-packages/werkzeug/_internal.py:96]
2025-01-20 20:56:14,836 ERROR: Str√°nka nenalezena: http://127.0.0.1:5001/static/images/3018/products/FA_3018_0031_189.png [in /Users/martinmikes/Downloads/my-directus-project/root/supplo.ai/app/__init__.py:129]
2025-01-20 20:56:14,837 ERROR: Str√°nka nenalezena: http://127.0.0.1:5001/static/images/3018/products/FA_3018_0032_77.png [in /Users/martinmikes/Downloads/my-directus-project/root/supplo.ai/app/__init__.py:129]
2025-01-20 20:56:14,841 INFO: 127.0.0.1 - - [20/Jan/2025 20:56:14] "[33mGET /static/images/3018/products/FA_3018_0031_189.png HTTP/1.1[0m" 404 - [in /opt/anaconda3/lib/python3.11/site-packages/werkzeug/_internal.py:96]
2025-01-20 20:56:14,841 INFO: 127.0.0.1 - - [20/Jan/2025 20:56:14] "[33mGET /static/images/3018/products/FA_3018_0032_77.png HTTP/1.1[0m" 404 - [in /opt/anaconda3/lib/python3.11/site-packages/werkzeug/_internal.py:96]
2025-01-20 20:58:46,391 INFO:  * Detected change in '/Users/martinmikes/Downloads/my-directus-project/root/supplo.ai/app/core/product_manager.py', reloading [in /opt/anaconda3/lib/python3.11/site-packages/werkzeug/_internal.py:96]
